language: r
r:
  - release
r: bioc-release
cache: packages

addons:
  apt:
    packages:
      - r-cran-tkrplot
      - tk-dev
bioc_packages:
 - Rhtslib
 - zlibbioc

r_build_args: --no-build-vignettes
r_check_args: --no-vignettes

notifications:
  email:
    on_success: change
    on_failure: change
